# Check Singular Matrix 

In [1]:
from CheckSingular import *
import numpy as np

## Test Case 1

In [2]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)

In [3]:
isSingular(A, print_steps=True)

[[ 1.   7.5 -2.5  3.5]
 [ 2.   8.   0.   4. ]
 [ 3.  12.   0.   5. ]
 [ 1.   3.   1.   3. ]]
[[ 1.          7.5        -2.5         3.5       ]
 [-0.          1.         -0.71428571  0.42857143]
 [ 3.         12.          0.          5.        ]
 [ 1.          3.          1.          3.        ]]
[[ 1.          7.5        -2.5         3.5       ]
 [-0.          1.         -0.71428571  0.42857143]
 [ 0.          0.          1.          1.5       ]
 [ 1.          3.          1.          3.        ]]
[[ 1.          7.5        -2.5         3.5       ]
 [-0.          1.         -0.71428571  0.42857143]
 [ 0.          0.          1.          1.5       ]
 [ 0.          0.          0.          1.        ]]


False

In [4]:
isSingular(A)

False

## Test Case 2

In [5]:
B = np.array([
        [0, 7, -5, 3],
        [0, 8, 0, 4],
        [0, 12, 0, 5],
        [0, 3, 1, 3]
    ], dtype=np.float_)

In [6]:
isSingular(B, print_steps=True)

[[ 0. 27. -5. 12.]
 [ 0.  8.  0.  4.]
 [ 0. 12.  0.  5.]
 [ 0.  3.  1.  3.]]


True

## Test Case 3

In [7]:
C = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)

In [8]:
isSingular(C, print_steps=True)

[[1. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 4. 4.]
 [0. 0. 5. 5.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 4. 4.]
 [0. 0. 5. 5.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 5. 5.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 0. 0.]]


True